{% set version = '0.7.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinydashboard
  version: {{ version|replace("-", "_") }}

source:
  fn: shinydashboard_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinydashboard_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinydashboard/shinydashboard_{{ version }}.tar.gz
  sha256: 51a49945c6b8a684111a2ba4b2a5964e3a50610286ce0378e37ae02316620a4e

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-htmltools >=0.2.6
    - r-promises
    - r-shiny >=1.0.0

  run:
    - r-base
    - r-htmltools >=0.2.6
    - r-promises
    - r-shiny >=1.0.0

test:
  commands:
    - $R -e "library('shinydashboard')"           # [not win]
    - "\"%R%\" -e \"library('shinydashboard')\""  # [win]

about:
  home: http://rstudio.github.io/shinydashboard/
  license: GPL-2
  summary: Create dashboards with 'Shiny'. This package provides a theme on top of 'Shiny', making
    it easy to create attractive dashboards.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - nsoranzo
