{% set version = "0.7.3" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-shinydashboard
  version: {{ version|replace("-", "_") }}

source:
  fn: shinydashboard_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shinydashboard_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinydashboard/shinydashboard_{{ version }}.tar.gz
  sha256: 641ce851846a58ecfe3b126b401f8e59d80f578451dd33f6cf1868bffea5144c

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-htmltools >=0.2.6
    - r-promises
    - r-shiny >=1.0.0

  run:
    - r-base
    - r-htmltools >=0.2.6
    - r-promises
    - r-shiny >=1.0.0

test:
  commands:
    - $R -e "library('shinydashboard')"           # [not win]
    - "\"%R%\" -e \"library('shinydashboard')\""  # [win]

about:
  home: http://rstudio.github.io/shinydashboard/
  license: GPL-2.0-or-later
  summary: Create dashboards with 'Shiny'. This package provides a theme on top of 'Shiny', making it easy to create attractive dashboards.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - nsoranzo
