{% set version = "0.6.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinydashboard
  version: {{ version|replace("-", "_") }}

source:
  fn: shinydashboard_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/shinydashboard_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/shinydashboard/shinydashboard_{{ version }}.tar.gz
  sha256: 1ee38f257433d24455426bc9d85c36f588735a54fbf6143935fed9cccb3bf193

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-htmltools >=0.2.6
    - r-shiny >=0.12.1
  run:
    - r-base
    - r-htmltools >=0.2.6
    - r-shiny >=0.12.1

test:
  commands:
    - $R -e "library('shinydashboard')"  # [not win]
    - "\"%R%\" -e \"library('shinydashboard')\""  # [win]

about:
  home: http://rstudio.github.io/shinydashboard/
  license: GPL-2
  summary: |
    Create dashboards with 'Shiny'. This package provides a theme on top of 'Shiny', making
    it easy to create attractive dashboards.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
