appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Oce91GCRteyYvJHpYjGbRKrCoMMkgjI0WIsI0NJdS9Ej/5zlXZXup/pZaqOBwNSbnkz3r3O4LeYX/dwV8xEOJubEIL7PqrBAzHteH3GlYn/1B2/2AkIPS+eVtpk5ykSqYebUUPY7lQrbv/BSCPdsvjwcK0gZqiuXI7XTy/MoK5dlG9SuMEPHB6tjkHnSq9KlVhjKLm5HkeArUj98Y4TpTbyF49aQQPMkuKnx+K8xz7U4XNjueUwz4hq6D6cWyB2x4xdrYXc8vFIq5JN07K2MynoLD6f4wsa+C6YYuCZY9QDnvP0Ggi21vLzChobLdFzeMfiBZF4D9LhY2i04uWoyvwtzuQ1YRNszJtCbcQZmf48pBuGCqIQivrvIXp49R27+mBVfdm+D5vB/XegPGZLJmPiEExI5c8cE71HzMJfB6TgsZiXQDBRt9863b8KPMHk0qO6bi9PMPX5K32ePMN6VWYLrHCIbSaMOs+9zzWiIMV0GhKHKtrFGpuGUX2SJt1oCMPjCvUFrE8oO5/pJ+ppWp7UudAdNUEe5x3lSJnV0ZZEPJafnF6AM+nlnze+7eIObm2rlqKKJ8C+BCSo2EkQB1wcM//uYZof4lLUVCLeIluGcGa2qH1KCYsbv8d/Et+2BgdXInOroZSsleFYv+MXXQod24yK2RrSbaPoRJjt6EhU=}
bot:
  automerge: true
